language: scala

scala:
  - "2.10.6"
  - "2.11.8"
  - "2.12.1"

jdk:
  - oraclejdk8
#  - oraclejdk7

node_js:
  - "6"

script: "$TRAVIS_BUILD_DIR/travis/build.sh"
sudo: false

matrix:
  exclude:
  - scala: "2.12.1" 
    jdk: oraclejdk7

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

env:
  global:
  - secure: U3+2FqtRx08MCt7O5RHnm30orqqBagkwq8kLTY5TQ3AKZKuhfZbO7ONWNHivTj8aHQwDCizTBAmx69Uik6KMb0rQuS6gsiyDUN/6PqY7twteUrQ52d3tBLXbyze9il0tvsKurQCxx/iEX15hHRseFn+YSva/9E4+HNYgL05oZKDdn64gHY0MBvkUgl0Y8KNV8skuLzT1W5xKU1xRWogyjyrVWZsceDgkYnuHj8hdJnVtouOXR7AziXov6bNi4AEG9x8tZ0CbpintRvbSu2tdLzufq3AEWHKJmqnuAYjbdoILFvWsVFiglP7mT4csZkG3+P0feZ5IFPD/rLs1OJesR30H43jXmjffDcqUccrTQhqMWGXU/gwK7tPkrCsXyEpuFHorgtNm6BH7BTOGVUUaBDFMghjiIZ+/cQV1UXbUfp+fmYjaB6OBaabxhqSzukXIDb59Ig0lL0NuXzfeaZcOONJAKWQ7DvMxfHckRq5KoDVQBtFAm8hZeQYCMngqu3bk/oxkdHORizVw8nmjaeBjxVOqYtPtDBBhMwaQ4bCZVDLw1NLzBGGtmkRoBKWmbHji1Fn26EIzaBqx/YSGDxOe6OEFi109/0l2/2U56gRoSRya0IQVS+1T7oHaUf1Sc3kbBLDot4dBS7qoJXDXnOeQY9e+r5rNbBWfF5jEFXvH+6c=
  - secure: mvUV8Zr25kdsNRXv7MGKs38MliKSreIGS02dcqLGwUwBZ8o09+JpQINKYhgXixIv3eX8C7ENQZxPq5hxUSeKh/pWJxl342rJ/x9Rel3TEa8XR16Rq4WhexVPvQ1/qDqBsuQyYd0wJoe9hPGq89jm820el/aw6JZciRqZmWjLbqgFejUevzxUVG5t7hrepk9JEXpCH0439KWRuhj5LOIU+16On9O4i2h0W53K/Pj2W1tw7ajxfNhi3ruYo7ZMY8gNkut1Q/IxzVcYqlGqllq7TA5UfMxm9iB74iN7HlNpnjYfv3JOrT3ds2yIlZ0QBP9KoRBfikjssbU3boLX5hVA4g3zWB7P3B5Xd8V9n/OEweC6cv3Au+SRc1i6aOT//ls/POoPzHLqUT9Si6wSmwKCpLMa0zru1Y+xkgs5PF6Qwohc1EneWtEZi05ox+gNuy3y9SvJH+9lJBafa0vvAeAIiT7y+1VMm8knIPbkyT8VCD+z9EiC+KuZIbzkWqwGaJDqZXI9pW7TTPPM4b2Fc7CAKmfGGljRYpCiGmahjycP1e7tGpndbhgz+huc/7u30iDl3jNvobb8OUQprNgWi/cgt1LbvfN88sQKBSZfbS6/NR7wA3f0tlk+BDbp+j1/umO11YBT/sVThnXdaja8UE4V9LDHI/FLgLieaLDcuggHLg4=
  - secure: rLSH6n3y4sRLt+ARn0ZhFUSDj5C+bBc+M6+M2826ir3/1vk5G+oUYQ0pbqlPNvouj5U29hXngnjCND0lsJCHs0Z5ONZrcWUAXcwT4tj20pLrY/wacjt7ZUJOn1FpWycEiTNd1HNfNOoddzmydPnZVO43CRKb+IjE8QFMCkkCjNCQx8oOobh8dO7F8VHUP5HwXPOx6CtF4kG9ZW+HNGKaDEDgLvGJayjTgr0TtC8nDoRmal6vhA1S2yHDypFNyXnPf1DmoELRW5po+ZX7MIq1LPCJU5s3B4gr8ipOkoaWkojEenXTvv6A0pDr8rmT4QIDJHVuLQqtYB/ST9cWo4UMCK9JY1y976k4SezZcd9qiK0P9e71aC9ZhL7PnMT/Hhp61gAcR4JUX0H5ZfkJmS4s9qqZYDgs9R/wnoUrc7nODkPkfmU/yBm6Timc6a9AI5tVPWvY7U/rEXh2s1EDY24oB/0dKETNT3zo4PAGX+D1iwcDY4vd9+WcysS8MBt+qtMev+Ql8pKn7L+zASp95mDslzW+F2RouAK7qpjFqawL/vs9EiyAchVGxn07S3XUnFJiJ+Zzc7njWqD5TEozafG+bj/V/qvtFu5wTAfB9R06x5tLNsPB/h3PXMejtbgFYRMUVkxGi7ALJchNmtGehzHbjKn5nZzuTX13RDqfF92s++g=
  - secure: c6M4XooyRxzobantxz4dYDW/J0tSxcdHpD4C7phKxOvsKln38xJho+JpOnZMZys0z2xynMvxvwnVp3H6kAi42GvXR28odJL9g4qOgnYyzvG7HIMl8QHZgYKTTaWwnj0oWXQRo+HbDOsQBb2pPqEEArkzF+jUWP+gNAuIOPSo3FUKR/RoSawSTExFwbCL1o7SnMQGHO8gMj7u8DmYTFOkH7OsjJbh/iGtuVbbIb+mIBy7zc/maujKB24TEFoFCuGL6CzmDrKl9FHx/h6j0KRQJlWxH9R45sCCnMsgm27Cs+21IBWu9kiD5pukcNgIj8ZIhUdWtwtE0UFGJ2z9Nuzr65QvpE2WB6F+jmBIx6p5V9qN0xWSb2/7kLU4gxfbIQI9oIJ1tdEJk5/JDelByH9rOiCvKjI1rwwHYJnVvhAUjIhRdNWep+o4D8B3ZSvwEy0c3rymJiMpA6qEKO2cns3id6FtBR8STg5QL208/TIHBOxzO5DsNCNttTkt97IY7NvSetdKJq4Xgxg1cK1DMn41hI8ViY7pLueWDhZS/QRwQeL0xeTCan40eXjqhwZUa8s34J/CsNxna44h3XC6XpWILYbrFVGb81qtsZTl+hbhuNPaJvfy4vX0eDcx/OVmeBffO7lEj/9oFSA26t6jvjM+OQMY7dkuIoQOYArK/jK2lww=
